
const ROSTER = [
  { id: 1,  name: "Angelo Ciarravino",  team: "Northwestern",           league: "NCAA",        position: "G"  },
  { id: 2,  name: "Kendrick Nunn",      team: "Panathinaikos",          league: "EuroLeague",  position: "G"  },
  { id: 3,  name: "Micah Robinson",     team: "TCU",                    league: "NCAA",        position: "G"  },
  { id: 4,  name: "Kobe Bufkin",        team: "Atlanta Hawks",          league: "NBA",         position: "G"  },
  { id: 5,  name: "Joan Beringer",      team: "Minnesota Timberwolves", league: "NBA",         position: "C"  },
  { id: 6,  name: "Nolan Traore",       team: "Brooklyn Nets",          league: "NBA",         position: "PG" },
  { id: 7,  name: "Kyshawn George",     team: "Washington Wizards",     league: "NBA",         position: "G"  },
  { id: 8,  name: "Yves Missi",         team: "New Orleans Pelicans",   league: "NBA",         position: "C"  },
  { id: 9,  name: "Robert Wright III",  team: "BYU",                    league: "NCAA",        position: "G"  },
  { id: 10, name: "Nils Cooper",        team: "UC Davis",               league: "NCAA",        position: "G"  },
  { id: 11, name: "Wenyen Gabriel",     team: "Bayern Munich",          league: "EuroLeague",  position: "F"  },
  { id: 12, name: "Justin Thomas",      team: "Bowling Green",          league: "NCAA",        position: "G"  },
  { id: 13, name: "Richard Barron",     team: "Providence",             league: "NCAA",        position: "F"  },
  { id: 14, name: "Sailou Niang",       team: "Virtus Bologna",         league: "EuroLeague",  position: "F"  },
  { id: 15, name: "Brice Sensabaugh",   team: "Utah Jazz",              league: "NBA",         position: "G"  },
  { id: 16, name: "Bilal Coulibaly",    team: "Washington Wizards",     league: "NBA",         position: "F"  },
  { id: 17, name: "JB Brown",           team: "North Carolina",         league: "NCAA",        position: "G"  },
  { id: 18, name: "Adama Bal",          team: "Westchester Knicks",     league: "NBAGL",       position: "F"  },
  { id: 19, name: "Sam Lewis",          team: "Virginia",               league: "NCAA",        position: "G"  },
  { id: 20, name: "Javonte Green",      team: "Detroit Pistons",        league: "NBA",         position: "F"  },
  { id: 21, name: "Langston Love",      team: "Georgetown",             league: "NCAA",        position: "G"  },
  { id: 22, name: "Desmond Watson",     team: "Free Agent",             league: "—",           position: "G"  },
];